version: '3'

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: grunner
    ports:
      - 8093:8093
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GITLAB_REGISTRY_ENABLED=true